// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCdbwtvKig-hH4yImP0Srrtld8UmQbpZw',
    appId: '1:330533452934:web:78145564f384b8fb292507',
    messagingSenderId: '330533452934',
    projectId: 'docappointmentapp',
    authDomain: 'docappointmentapp.firebaseapp.com',
    storageBucket: 'docappointmentapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ96pZQmrbEVqSfT1IgQkCYKPKjrJbYfo',
    appId: '1:330533452934:android:6da3cc0ed2079dce292507',
    messagingSenderId: '330533452934',
    projectId: 'docappointmentapp',
    storageBucket: 'docappointmentapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Xkh_Vakshct_OOhR8T-IN1MIy4Xc1Co',
    appId: '1:330533452934:ios:5ef357ca27e28405292507',
    messagingSenderId: '330533452934',
    projectId: 'docappointmentapp',
    storageBucket: 'docappointmentapp.appspot.com',
    iosBundleId: 'com.example.smithackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Xkh_Vakshct_OOhR8T-IN1MIy4Xc1Co',
    appId: '1:330533452934:ios:5ef357ca27e28405292507',
    messagingSenderId: '330533452934',
    projectId: 'docappointmentapp',
    storageBucket: 'docappointmentapp.appspot.com',
    iosBundleId: 'com.example.smithackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCdbwtvKig-hH4yImP0Srrtld8UmQbpZw',
    appId: '1:330533452934:web:6c02e5a83ed758e9292507',
    messagingSenderId: '330533452934',
    projectId: 'docappointmentapp',
    authDomain: 'docappointmentapp.firebaseapp.com',
    storageBucket: 'docappointmentapp.appspot.com',
  );

}